### ISSUE TITLE
Hello thank for sharing

### ISSUE THREAD

**Issue by mariobigboy** [jhonatanmt83/odontograma#1]
How can I save changes?

**Comment by jhonatanmt83** [comment]
Hi, 
This data is saved in localStorage whit keys as format "A-B-C" where:
A => Is # of tooth.
B => Is # of section in tooth starting of top=1, right=2, bot=3, left=4 and center=5; in case is refered of all tooth is 0.
C => It's type of process done 1=>FRACTURE, 2=>RESTORATION, 3=>EXTRACTION, 4=>BRIDGE.

Additionally for bridge the format is "A-B-C-D" where D is the end tooth number.

For each key the value is array parsed to string type "A,B,C,E,0" where E is Date.now() in time is added, 0 is permanent (without use) and is bridge add # of end tooth.
