### ISSUE TITLE
Hola buen dia

### ISSUE THREAD

**Issue by CesarDiiaz** [jhonatanmt83/odontograma#2]
Una pregunta, estoy  presentando una dificultad con el código del odontograma que cuando bajo el scroll no me esta tomando los dientes es como si estuviera en una posición fija

**Comment by jhonatanmt83** [comment]
Hola, efectivamente lo que toma son posiciones fijas basandose en el elemento div#canvasesdiv y en el canvas#myCanvas tomando su offsetLeft y offsetTop para poder definir los tramos dibujados dentro del canvas, en realidad este codigo lo deje a medias, pero espero en un futuro cercano poder subir un field de odontograma que estube desarrollando para django.
